### PR TITLE
Compile on recent hhvm (again) since 91e07b9

### PR DESCRIPTION
**Pull request by tlevi**
This include has gone from hhvm, doesn't seem necessary.

### CODE REVIEW

**Comment by moberemk** [comment]
I've tested this against my company's Ubuntu+HHVM vagrant box and it doesn't seem to cause any issues for us either, can this please get merged in @simonwelsh?

**Comment by digitalsparky** [comment]
I tried this patch, however I'm getting: 

php: symbol lookup error: /etc/hhvm/extensions/pgsql.so: undefined symbol: _ZNK4HPHP9ArrayData6existsEl

**Comment by moberemk** [comment]
Which HHVM version/which Postgres function? I haven't noticed anything like that yet myself.

**Comment by digitalsparky** [comment]
Latest Ubuntu package release (3.7.0), worked perfectly fine before the update, running a 'migrate' with Laravel (which creates tables, indexes, etc). - Laravel uses PDO.

**Comment by digitalsparky** [comment]
Thinking about it, it may just be that hhvm-dbg wasn't installed, will have to check again tomorrow.

**Comment by mwpastore** [comment]
I can confirm this on a brand new install of Ubuntu 14.04 LTS with libpq 9.3.4 and hhvm 3.7.0. Running PDO::__construct with an options array, PDO::query, or PDO::prepare seems to trigger the missing symbol error. I'm going to rewrite some code to use the non-PDO style and see if that changes anything.

**Comment by simonwelsh** [comment]
Sigh. I had thought I'd pushed my change.

I've deleted the pgsql.h file entirely, so this is no longer an issue.

**Comment by Mirza-dMags** [comment]
I'm having same error with fully updated Ubuntu 14.04 and hhvm 3.8.0:

"/etc/hhvm/pgsql.so: undefined symbol: _ZNK4HPHP9ArrayData6existsEl"

**Comment by iangcarroll** [comment]
I have the same issue as well.

# hhvm --mode server --user=www-data --config=/etc/hhvm/server.ini
hhvm: symbol lookup error: /etc/hhvm/pgsql.so: undefined symbol: _ZNK4HPHP9ArrayData6existsEl

# hhvm --version
HipHop VM 3.8.0 (rel)
Compiler: tags/HHVM-3.8.0-0-gbb32f8d645b28561d8491870c44730b9b3f08d35
Repo schema: 74bee5d310450724cfd49245fd6c2e1e4323b10a

**Comment by akuseru** [comment]
The fix for that undefined symbol is in the open pull request #93

**Pull request closed without merging**
