### PR TITLE
Fix #56: pg_fetch_assoc returns NULL at end of result instead of FALSE

### LINKED ISSUE #56: pg_fetch_assoc returns NULL at end of result instead of FALSE
As documented in [1], pg_fetch_assoc should return false if there are no more rows. The current implementation, however, returns NULL.

This also affects pg_fetch_object, as it uses pg_fetch_assoc internally.

[1] http://php.net/manual/de/function.pg-fetch-assoc.php

### PR DESCRIPTION
**Pull request by dstelter**

### CODE REVIEW

**Comment by mssola** [comment]
IMHO this is not the proper fix. For starters, if we're not in Hack friendly mode, the return value will always be false on error for the `pg_fetch_array` function. So even this line of yours will fail:

```cpp
if (res.isNull()) {
```

The real deal lies on the definition of this function on the `ext_pgsql.php` file. The return type should be mixed, not an array. Note, for example, that MySQL does this: https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext/mysql/ext_mysql.php#L260

I've applied this fix and tested it on my repo: https://github.com/mssola/hhvm-pgsql/commit/1f269a1d5fa72651d860b8ffd3200188001ae948 . Sadly I'm on my `beyond` branch and it's a bit tangled up for me to apply this fix here ...

Moreover, I'll have to investigate which other functions are affected because of this `mixed vs array` situation (and write tests for them).

**Comment by dstelter** [comment]
Good point, thanks for the input. Your proposed fix works perfectly on the stable branch as well.
Should I submit another pull request to incorporate your patch or do you want to do this at a later stage?

**Comment by mssola** [comment]
I'd prefer to do it later with fixes for other functions as well. Maybe you can close this pull request but leave your issue open ?

**Comment by mssola** [comment]
@dstelter there you go: #58  ;-)

**Comment by dstelter** [comment]
Awesome! :-)

**Pull request closed without merging**
